### ISSUE TITLE
Add option to emit a full-formed java library project from Thrift input

### ISSUE THREAD

**Issue by benjamin-bader** [microsoft/thrifty#120]
It would be neat to have `thrifty-compiler` just spit out a ready-to-compile project.  

Who knows that _that_ API would look like; will think about it for now.

**Comment by hzsweers** [comment]
what's the idea behind this? We basically do this internally and could possibly help advise on the API

**Comment by benjamin-bader** [comment]
The idea would be to accept `.thrift` as input, do codegen, and emit a fully-formed Gradle/Maven/etc project.  It seems to me that this would make consuming the generated code simpler - just copy the module over to your project and add it to settings.gradle.  Even better, you could just build and push to a Maven repo.

I haven't really thought much about the API since filing this issue, but looking back I wonder if it wouldn't make more sense as part of a Gradle/Maven/etc plugin.

What's the story with your internal tooling - how do others make use of the generated  projects?

**Comment by gotev** [comment]
I already have something similar. Instead of generating the whole project files (which changes very frequently and will be hard to maintain) I've created a basic library project with android studio and tuned it a little bit. Here it is: https://github.com/gotev/android-base-library

The workflow to create a new library project is that you clone the repo, rename the package and you have a library module together with an example project which uses it, ready for deployment using Bintray as gateway for both jCenter and Maven Central. It works great for what I need and I currently use it in production for many libraries. For an internal project where I work I cloned that same repo, added this to the library module gradle's task:
```groovy
task generateThrift(type: Exec) {
    commandLine 'sh', '-c', 'cd ..; ./generate-thrift'
}

preBuild.dependsOn generateThrift
``` 
And then included the following `generate-thrift` in the top-level directory (I know, it works only on Unix boxes):
```bash
#!/bin/bash
THRIFTY_VERSION="0.4.2"
THRIFT_DIR="thrift"
GEN_OUTPUT="library/src/main/generated"

if [ ! -f thrifty-compiler.jar ]; then
    echo "Downloading Thrifty $THRIFTY_VERSION from Maven Central..."
    url="http://repo1.maven.org/maven2/com/microsoft/thrifty/thrifty-compiler/$THRIFTY_VERSION/thrifty-compiler-$THRIFTY_VERSION.jar"
    echo "$url"
    curl -L "$url" -o thrifty-compiler.jar
fi

echo "Removing generated files directory.."
rm -rf "$GEN_OUTPUT"
mkdir -p "$GEN_OUTPUT"

echo "Generating Android client Thrift bindings..."
java -jar thrifty-compiler.jar --use-android-annotations --out="$GEN_OUTPUT" "$THRIFT_DIR"/*
```
After this setup, you basically just put your Thrift IDL files inside the `thrift` directory (either manually or by adding a submodule) and when you hit build inside android studio, the generation happens before the build and you are ready to use generated files inside the project (or to deploy them to your favorite maven repository).

The better option will be to have a gradle plugin for thrifty, which will allow to have something like this:
```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.microsoft:thrifty-gradle-plugin:1.0.0'
    }
}

apply plugin: 'com.microsoft.thrifty-gradle-plugin'
```
```groovy
thrifty {
  androidAnnotations true
  inputDir file('${project.projectDir}/src/main/thrifty')
  outputDir file('${project.buildDir}/generated/source/thrifty')
}
```
What are your thoughts?

**Comment by hzsweers** [comment]
Ben and I actually talked about this in person over coffee a few weeks back. I think the gist of this is more about generating projects and not just having a gradle wrapper around the compiler.

**Comment by gotev** [comment]
@hzsweers so you mean something similar to what Cordova does. My only concern about that approach is that if Google or Gradle team decides to change the file formats or the structure, an entire project generation tool will be harder to maintain in the future.

**Comment by benjamin-bader** [comment]
With #356, we have a Gradle plugin that basically obviates this issue.  Who needs a generated Gradle project to house generated thrifts, when you can just plug them in to your existing Gradle project at build-time?
