### ISSUE TITLE
Proposal: Add configurations for schema loading

### ISSUE THREAD

**Issue by hzsweers** [Microsoft/thrifty#144]
Totally out of self-interest from my experience, but might make it easier to adopt thrifty's schema: some configuration for controlling how strict the parser is.

Some ideas:
- duplicate field IDs
- using keywords as names

**Comment by hzsweers** [comment]
yeah I'd love to take a look. That was the part I actually wasn't sure about, the duplicate field IDs would be reasonably easy to flag

and totally understandable :)

**Comment by benjamin-bader** [comment]
I've pushed the branch to my personal fork: https://github.com/benjamin-bader/thrifty/tree/syntax/escaped-literals

It implements an "escaped identifier" syntax for enum members where surrounding an identifier with square brackets circumvents checking for reserved keywords, e.g.

```
enum Foo {
  [struct] = 1,
  BAR = 2
}
```

The main point is that the antlr definition gets a new `ESCAPED_IDENTIFIER` token, because (due to the lexing algorithm) literals that appear in parse rules (e.g. `struct`) are so-called "implicit" tokens, and aren't matched by catch-alls like `IDENTIFIER` which are defined later on in the file.  Using an escaping syntax like this sidesteps the issue, because `[struct]` never appears in the grammar.

If you wanted to allow non-escaped keywords, we'd need to pull literals into explicit tokens, like `STRUCT : 'struct';`, use those everywhere in the grammar, and then make identifier into a parse rule `ident : STRUCT | ENUM | ... | IDENTIFIER`.  It would be a lot of work, but doable.

Not sure how much of that makes sense; if it doesn't, let me know!

**Comment by benjamin-bader** [comment]
@hzsweers Do you still have use-cases for any of these?  I'll close this if not.

**Comment by hzsweers** [comment]
I think it's safe to close for now, being strict is probably a better thing to do
