### ISSUE TITLE
Json Protocol support

### ISSUE THREAD

**Issue by reisub** [Microsoft/thrifty#154]
Would you be open to a PR implementing json protocol support, based on Apache Thrift implementation? This functionality would be quite useful for easy request/response logging in development.

**Comment by benjamin-bader** [comment]
Possibly!  I know there are a few different JSON protocols floating around out there; which did you have in mind?

**Comment by reisub** [comment]
I was thinking of [this one](https://git1-us-west.apache.org/repos/asf?p=thrift.git;a=blob;f=lib/java/src/org/apache/thrift/protocol/TJSONProtocol.java;h=fd54fdf462cfcf4136a8a8447060a8b9ff3d12e6;hb=HEAD).

Do you know of a more useful one?

**Comment by benjamin-bader** [comment]
There's the [simple JSON protocol](https://git1-us-west.apache.org/repos/asf?p=thrift.git;a=blob_plain;f=lib/java/src/org/apache/thrift/protocol/TSimpleJSONProtocol.java;hb=HEAD), which is less useful than the one you linked because IIRC it is a write-only protocol that doesn't encode enough info to read its own output.

The one you linked is better-suited for us.  If it's useful to you, I'm happy to consider new protocol support.

**Comment by reisub** [comment]
Great, I'll get to work!
