### ISSUE TITLE
Optionally suppress generated Builder types

### ISSUE THREAD

**Issue by bangarharshit** [Microsoft/thrifty#158]
```thrift
// Let's call this example.thrift

namespace java com.foo.bar

struct Query {
  1: required string text,
  2: optional i64 resultsNewerThan
}

struct SearchResult {
  1: required string url,
  2: required list<string> keywords = [], // A list of keywords related to the result
  3: required i64 lastUpdatedMillis // The time at which the result was last checked, in unix millis
}

service Google {
  list<SearchResult> search(1: Query query)
}
```

In the example above we need builder only for `Query` as the value for the search result is populated by deserializer. Looking at the code there is no easy way to distinguish if the model is `request/response` type.  Any idea on how to go around it?

**Comment by benjamin-bader** [comment]
That's an interesting question.  There isn't any way to strip out the `Builder` types; the generated adapter code uses them to implement deserialization.

I'd never thought about `request/response` types before, because Thrift itself makes no such distinction; it's more of an application-specific label.  It's an interesting idea though, and one I could see being implemented, for example:

```thrift
struct SearchResult {
  ...
} (thrifty.nobuilders = "true")
```

It would be a relatively big job, and I don't have the time to implement it.  I'd be happy to talk design and coach someone through a PR, though!

**Comment by bangarharshit** [comment]
Great point. I think this optional annotation will be applicable only to `structs`.  At a higher level, my understanding is that it should be checking annotation to remove the code when building struct (but I might be missing other things).

Can you give an outline of the approach and if there are edge cases to look for?

**Comment by benjamin-bader** [comment]
This sort of thing would apply to structs, unions, and exceptions - all of these have generated builders.

The implementation would be "straightforward" - in `ThriftyCodeGenerator#buildStruct`, add a separate code path for `nobuilder` types.  The tricky part will be modifying `GenerateReaderVisitor`, the class that is responsible for generating deserialization code.  It assumes that there is a `builder` involved, which would no longer be guaranteed - either we'll need a variant of this visitor that doesn't use builders, or this one should be rewritten to _never_ use builders.

The latter approach would be simpler, and could potentially make generated code much more proguard-friendly.

I haven't thought deeply about this, so it's possible that I've missed an important edge-case here.

**Comment by bangarharshit** [comment]
I am working on a PR for this. Will test it thoroughly and send it by the weekend.

**Comment by benjamin-bader** [comment]
This is implemented in the newly-landed Kotlin codegen feature.  I'm not inclined to make any efforts for generated Java code - thrifty-java-codegen is sufficiently complex that it would be a big job for which I don't have time.

Since there hasn't been any action here since January, I'm inclined to close this issue.  Are you still planning on doing something here, or is Kotlin good enough?

**Comment by bangarharshit** [comment]
Kotlin should be enough. It makes sense to close it.
