### ISSUE TITLE
Location#path should have relative path to an include-path root 

### ISSUE THREAD

**Issue by benjamin-bader** [microsoft/thrifty#237]
It seems that `Location#path` is always just `filename.thrift`; this is not very useful.  We'd intended for it to convey the relative position of the file, but from whose perspective?  Not that of the including file, because a file can be included more than once.

It should probably be relative to one of the paths in the include search-path (which includes the compiler's working directory, fyi).  Not sure how exactly to go about this, since we've no tests to verify this behavior and it has likely been broken for a very long time.

**Comment by jparise** [comment]
This is because `Location#path` is just a string attribute. `Location` itself has a `toString` implementation that builds a more useful string representation using `base`, `path`, `line`, and `column`.

I think a good outcome would be making `base` a "smarter" relative representation of the root directory. Then we could reliably use `Location` directly (with `toString`).

**Comment by benjamin-bader** [comment]
I think we agree here; Location is intended to be a smarter relative representation.  In practice, the parser doesn't seem to be instantiating Locations in a smart way; this should be fixed.  Currently, only the Loader has knowledge of root directories - possibly, this is the place to fix it.
