### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by thorbenprimke** [microsoft/thrifty#315]
@benjamin-bader I was looking to upgrade our thrifty dependency and I was wondering if you have plans to release an official update of the library? 

I tried the snapshots maven dependency but it's not working for CI builds (403 error from sonatype). I can work around this by hosting the dependency locally. 

Let me know what your plans are. Thanks!

**Comment by benjamin-bader** [comment]
I do have plans!  My attention has been elsewhere lately, but we're overdue for a 2.0.0 release.  I feel a little uncomfortable declaring 2.0.0 because I don't think anyone is actually using the code I've added for Kotlin unions.  If it helps, I'd be happy to push an RC for you.

I'm surprised and concerned that you're getting a 403 from Sonatype; I hadn't thought that there was any access control at all on their snapshot repo.  Do you only see that in your CI builds?

**Comment by thorbenprimke** [comment]
Awesome to hear. 

Yea, an 2.0 RC or 1.0.1 via mavenCentral / jcenter would be ideal. 

I'm only seeing the 403 on our CI machines. We are running Buildkite (on AWS instances - I believe). The CI kicks of five parallel jobs (build, 3x lint, unit test) and pretty consistently only one of them is able to retrieve the dependency and the others get the 403 error - maybe it's some rate limiting by IP address from sonatype's end. 

```
> Could not resolve com.microsoft.thrifty:thrifty-compiler:1.0.1-SNAPSHOT.
   > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/thrifty/thrifty-compiler/1.0.1-SNAPSHOT/maven-metadata.xml.
      > Could not get resource 'https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/thrifty/thrifty-compiler/1.0.1-SNAPSHOT/maven-metadata.xml'.
         > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/thrifty/thrifty-compiler/1.0.1-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

**Comment by benjamin-bader** [comment]
You didn't feel the break because you're not using thrift unions, at least not with Kotlin codegen :)

To my embarrassment, I'd totally forgotten to implement this in Kotlin for 1.0.0, resulting in barely-working code.  The new implementation is good, but not at all compatible.  Technically that means 2.0.0, even if (nearly?) nobody is using unions these days.

I'll make an RC release tomorrow and update here.

**Comment by thorbenprimke** [comment]
![image](https://user-images.githubusercontent.com/741767/57382457-ff9def00-717a-11e9-9d66-ad9f2e63f09e.png)

**Comment by benjamin-bader** [comment]
2.0.0-RC1 is out to Sonatype, and should be visible in Maven Central in the next 15-60 minutes.  Usually it's faster, but today their server seems dog-slow so ¯\_(ツ)_/¯
