### ISSUE TITLE
Thrift Server Support

### ISSUE THREAD

**Issue by chaviw** [Microsoft/thrifty#34]
Nice work overall on the project! One thing I noticed missing in the library is support for thrift server, similar to `TSimpleServer` in the apache library. Are there plans to add those or are you assuming most thrift servers will be hosted on actual server and not on the Android client.

A specific use-case for this is when communicating with hardware from the Android device. The Android device may want to act as the server to retrieve data

**Comment by benjamin-bader** [comment]
Thanks!  An astute observation and a valid use-case.

Server support is problematic because of how we treat requiredness.  It's a subtle but important deviation from the Thrift spec, which we've taken because it allows us to get rid of all those `isSet`, `setIsSet`, etc methods.  Basically there are legal states for thrift objects that Thrifty cannot represent - they don't arise in client usage, but can and do appear in server implementations.

So, without fundamentally changing the project in ways we aren't willing to do, we can't make a spec-compliant server.
