### ISSUE TITLE
Rules around comment parsing are unclear

### ISSUE THREAD

**Issue by hzsweers** [Microsoft/thrifty#38]
The following struct fails to parse:

```thrift
struct SomeRequest {
    /** Here's a comment. */
    1: required UUID clientUuid

    /**
     * Here's a longer comment.
     * One two lines.
     */
    2: optional string someOtherField

    /**
     * Here's another longer comment.
     * Also on two lines.
     */
    3: optional UUID someField

    /** Here's another single line that works fine. */
    4: optional UUID adminUuid
}
```

This fails with the following error:

```
trailing comment must be closed on the same line
```

Could you explain where the issue is in these comments? It seems like the formatting is fine, and the error message isn't really clear since I see several tests with multiline comments like this.

**Comment by benjamin-bader** [comment]
Eh, no need to ask about rules - you've found a (rather large and obvious) parser bug.

It looks like the parser is attempting to parse "trailing" comments where none exist, probably because you have left off the optional separator (`;` or `,`) at the end of your fields.

I'd love to find more time for #30, which holds the promise of eliminating this class of bug entirely.

**Comment by hzsweers** [comment]
oof, yeah that's a big task. Is there anything I could contribute in a PR to fix this one by itself for now? It's popped up as a blocker for me since server folks do this everywhere :(

**Comment by benjamin-bader** [comment]
Sure, I'd be glad for the help!

The bug is in ThriftParser.java, in the part that reads fields.  Probably it is skipping over whitespace that should not be skipped - or, more annoyingly, *should only conditionally be skipped*.  Probably an easier way to approach it would be to only conditionally parse trailing documentation.

**Comment by hzsweers** [comment]
What would be the condition for parsing trailing documentation?

**Comment by benjamin-bader** [comment]
"Trailing documentation" is just a single-line comment following the end of a field definition, including annotations.  It is visually easy to distinguish from regular comments:

```thrift
struct Example {
  1: required string foo (redacted = "true") // this is trailing documentation following an annotation

  /** But this is not! */
  2: required string bar
}
```

The distinction between the two is whether there is a newline between the comment and the end of the field.  It turns out that (for me at least) this is tricky in code.  I'm guessing that, since your example does not include annotations, the annotation-parsing code is skipping over the newlines between fields.

Probably we could get away with just checking what line we are on before parsing annotations, and skipping the trailing-doc check if we are on a different line after the annotation code.  Dirty but effective.

**Comment by hzsweers** [comment]
Alright, I'll take a look when I get some time this week. Thanks for the insight!

**Comment by hzsweers** [comment]
Been swamped at work, but still planning to look into this!

**Comment by hzsweers** [comment]
I took a shot at fixing this, but I actually can't even get normal builds to work for the project in IntelliJ. Anything specific you recommend for project setup?

**Comment by benjamin-bader** [comment]
Yes, I've been periodically irritated by the same problem.  My solution is to do a command-line build first, which does the right things and generates the AutoValue sources.  After that, IntelliJ stops complaining.

**Comment by hzsweers** [comment]
ahh good point. I'll try that

**Comment by seanabraham** [comment]
@hzsweers did you have any luck fixing this? I might be interested in taking a look too if you weren't able to get something work.

**Comment by hzsweers** [comment]
I haven't really had time to, so feel free to take it on!
