### ISSUE TITLE
include not found with 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by shashachu** [microsoft/thrifty#422]
The directory a thrift file is in is no longer added to the list of include paths, so if it's not explicitly added to the search paths, any includes in the same directory will not be found. I'm not sure if this was an unintended side-effect that was fixed, or if the new behavior is a bug.

Sample repro:

Create files:
`thrift/bar/bar1.thrift`
`thrift/bar/bar2.thrift`

`bar1.thrift`:
```
include "bar2.thrift"
```

```
$ java -jar thrifty-compiler-3.0.0-SNAPSHOT-all.jar --out=/tmp/thrifty-test /Users/shasha/Desktop/thrift/bar/bar1.thrift 
java.io.FileNotFoundException: Failed to locate bar2.thrift in [/Users/shasha/Desktop, /Users/shasha/Desktop, /Users/shasha/Desktop/thrift/foo]
--> Included from /Users/shasha/Desktop/thrift/bar/bar1.thrift
```

Reverting #416 fixes the issue.

**Comment by benjamin-bader** [comment]
Thanks for flagging the issue.  Considering the including file's directory is certainly intentional, and we don't want to break that!  I think I understand the issue now.  There are actually two bugs at play here, both in `Loader`, and both revolve around unintentionally depending on the behavior fixed in #416 - that is, they assume `Location#base` is always the full path to a file's parent directory.

The first is that we plain broke prepending an including file's directory to the include path, because we actually prepended `Location#base`.  Fixing that exposes another bug in the private method `findFirstExisting`, which also operates under that same assumption.

Will have a fix shortly.
