### ISSUE TITLE
Options to ignore certain struct fields/properties during code generation?

### ISSUE THREAD

**Issue by theta3** [microsoft/thrifty#445]
Hello, I'm looking to ignore struct fields of certain types based on type names (these fields are not used in Java generated code)

If I try to do this in the implementation of `KotlinTypeProcessor`, e.g. calling `TypeSpec.Builder.propertySpecs.removeIf { }`, it's too late.

I can do this easily in the `StructType` constructor:
`````
internal constructor(element: StructElement, namespaces: Map<NamespaceScope, String>)
            : super(UserElementMixin(element, namespaces)) {
        this.structType = element.type
        this.fields = element.fields.filter { /* CONDITION */ }.map { Field(it, namespaces) }
    }
`````
But I want to make this more generic for everyone. How do I pass an option from `ThriftyCompiler` so it can be picked up here?

Thanks,

**Comment by jparise** [comment]
This could be a good use case for Thrift annotations.

**Comment by benjamin-bader** [comment]
@theta3 are type processors "too late" because generated code references those properties?  If that's the case I agree with @jparise; we could add a `(thrifty.ignore = true)` thrift annotation to those fields in the .thrift files.

I'm guessing this is regarding Outlook telemetry.  I worry a bit that nobody remains who knows this codebase, so IMO this would be a great first step for you or whoever owns the codegen bits.  I'm happy to guide you.  I see a few likely spots where you might act on this new annotation.

The first spot is within `ThriftListener.parseFieldList`; this is the earliest spot in the compiler where you have a field and its annotations.  I don't necessarily think it's your best option because it feels like an undesirable mixing of responsibilities.

Another, better, option might be to alter `StructType` such that when it's constructed, it filters out fields that carry this annotation.  I'm not sure it's the right choice either; intuitively, I fear throwing away information (the fields) that we might otherwise want.

Finally, the hard-mode option is to update the code-generators themselves, both Kotlin and Java, such that they ignore fields with this annotation.  Although it would also carry the most maintenance burden, this option is my preference.

**Comment by benjamin-bader** [comment]
I have to admit that I'm curious.  What's the point of generating code but omitting some of the fields?

**Comment by jparise** [comment]
If we pursue the `(thrifty.ignore = true)` annotation path, it would be (most) useful if it could apply to as many schema elements as possible. That might argue for a generic filtering pass over the parse tree rather than an struct-specific implementation.

Also, this does open up the possibility of one struct reference another struct that has been ignored, in which case we'll produce uncompilable code. It would be nice to identify those cases explicitly so we can provide a useful error message for those cases, but I don't know if that's a strict requirement.

**Comment by benjamin-bader** [comment]
Gotta be honest, I'm not really a fan of this idea personally, but also don't have the context from which it arises.  It opens up a _ton_ of edge cases, as you mentioned.

For the specific edge case of referencing ignored fields, I'm totally OK with generating invalid code.

**Comment by theta3** [comment]
Hi @benjamin-bader and @jparise  ,  thank you for your responses:
1. In the implementation of `KotlinTypeProcessor`'I added the below code but it has no effect, the field still gets generated
`````
override fun process(type: TypeSpec): TypeSpec? {
return with(type.toBuilder()) {
            ...
            propertySpecs.removeIf {
                            it.name.endsWith("TARGET_FIELD_NAME")
                        }
            ...
            build()
        }
}
`````
What do you think?
2. My current working implementation is to modify Thrifty StructType constructor:
`````
internal constructor(element: StructElement, namespaces: Map<NamespaceScope, String>)
            : super(UserElementMixin(element, namespaces)) {
        this.structType = element.type
        this.fields = element.fields.filter { /* CONDITION */ }.map { Field(it, namespaces) }
    }
`````
But I am told that this is too specific and can't be merged into the official public Thrifty repo.
3. The original requirement is we want to add some enum metadata into each struct for tracking purpose. It's not free form like code comment and it won't be used in the host application so it's not needed in generated code. This is the first time I hear about Thrift annotations and I couldn't find a lot of documentation about them

**Comment by benjamin-bader** [comment]
Honestly, annotations sound like the perfect vehicle for metadata.  Here's an example of thrift annotations:

```thrift
struct SomeEvent {
  1: string foo ("thrift.ignored" = "true"); // <-- this is a "field" annotation
  2: string bar;
} ("meta.one" = "foo", "meta.two" = "bar");  // <-- this is a "struct" annotation
```

**Comment by theta3** [comment]
Are annotation key and value free form? Is there a way to restrict the values, key name?

**Comment by benjamin-bader** [comment]
Annotations are free-form.  Thrift has no way to "strongly type" annotations.  If you want to add guarantees around annotation keys/values in your IDL, then that's a very different feature request - and one I'm much happier to entertain.

**Comment by benjamin-bader** [comment]
What do you want to do with that metadata though?  Like if it isn't being used in codegen, what _are_ you planning to do with it?

**Comment by theta3** [comment]
right now, they are Thrift struct field and I'm using antlr to read them and perform actions based on this parsed information. For example, "find all structs who have this field's value of X and go perform this extra work over here". Work is not limited to codegen, but can be automation such as sending emails, generating lists, etc.

**Comment by benjamin-bader** [comment]
Got it; are you using thrifty's antlr grammar?  It understands annotations.  Our type models all preserve annotation data as well, so you could easily incorporate `thrifty-schema`'s `Loader`, for example, into your program and read the metadata that way.

**Comment by theta3** [comment]
Right now I'm using this https://github.com/antlr/grammars-v4/blob/master/thrift/Thrift.g4 to generate antlr Python lexer and parser to read the .thrift file. I guess I can use Thrift annotation and leverage the antlr lexer and parser to "compile" the annotation, aka making sure the annotation keys and values are expected?

**Comment by benjamin-bader** [comment]
That sounds like a perfect job for a Python program :)

**Comment by benjamin-bader** [comment]
Given your emoji reaction, I'm going to assume that this (using your existing Python program to read annotations and validate them) is adequate, and will tentatively consider this issue to be resolved.  Please let me know whether that's true, and if not, let me know and we'll figure out what it takes to help you succeed.

**Comment by theta3** [comment]
Hi. yes, I think I will be fine without changing thrifty. Thank you for all your help
